export const randomMsg = [
  "keep going!",
  "never gonna give you up...",
  "one more rep!!",
  "your cat will bite you if you fail now",
  "you can do it!",
  "shut up and grind",
  "future you is watching—don’t embarrass them",
  "tiny reps beat tiny excuses",
  "pain is the tax for progress",
  "discipline first, feelings later",
  "last set, best set",
  "your bed is plotting—prove it wrong",
  "no one cares—work harder (politely)",
  "consistency is the cheat code",
  "form first, ego second",
  "make tomorrow jealous of today",
  "rep it like you mean it",
  "hungry? good—eat the reps",
  "comfort zones are cardio for cowards",
  "breathe, brace, conquer",
  "you don’t need easy, you need done",
  "strength is a decision repeated",
  "be the reason yesterday wasn’t for nothing",
  "this set pays rent for your goals",
  "progress > perfection",
  "your future PR says thanks",
  "proof of effort due now",
  "no finish line, just milestones",
  "move the body, quiet the brain",
  "this is where most quit—don’t",
  "show up, show out",
  "stack small wins",
  "calm face, violent reps",
  "outwork your mood",
  "one minute of courage, go",
  "you vs you—round 13",
  "make it count, not cute",
  "discipline > motivation",
  "start. then don’t stop",
  "hard today, easy tomorrow",
  "progress is slow, quitting is slower",
  "today’s grind is tomorrow’s pride",
  "discipline is built one rep at a time",
  "show up tired, leave stronger",
  "don’t wait for perfect, chase consistent",
  "tiny steps become giant leaps",
  "your only rival is yesterday’s you",
  "the gym doesn’t ask for talent, just effort",
  "pain today, power tomorrow",
  "your future self is cheering already",
  "stack enough small wins to bury doubt",
  "hard now, legendary later",
  "strength doesn’t ask for permission",
  "every drop of sweat is an investment",
  "choose progress over comfort",
  "strength > mood",
  "your body adapts, your excuses don’t",
  "prove comfort wrong",
  "effort compounds daily",
  "you’re stronger than Netflix",
  "consistency beats talent",
  "don’t lift for claps, lift for legacy",
  "fuel the reps, not the doubts",
  "lazy today, sorry tomorrow",
  "don’t fear sore, fear stagnant",
  "the grind never ghosts you",
  "your sweat is your autograph",
  "you don’t need hype, you need habit",
  "get addicted to progress",
  "make struggle your spotter",
  "failure’s just pre-progress",
  "your muscles understand effort, not excuses",
  "hard work cashes out in strength",
  "the gym is honest—give or get nothing",
  "stop whining, start grinding",
  "the iron doesn’t care about your feelings",
  "weak excuses weigh more than plates",
  "you want results? shut up and lift",
  "comfort zones breed cowards",
  "the barbell doesn’t negotiate",
  "gravity doesn’t take days off",
  "every rep skipped is betrayal",
  "don’t pet excuses, strangle them",
  "the floor isn’t crying, why are you?",
  "rest is for corpses, not trainees",
  "no pain? then you’re faking it",
  "you’ll rest when your muscles quit screaming",
  "cry in the gym or cry in the mirror",
  "push like the dumbbell owes you money",
  "reps don’t count till they hurt",
  "be allergic to giving up",
  "make the weights regret existing",
  "you can rest when you’re shredded",
  "prove gravity wrong again",
  "don’t fear the barbell, fear regret",
  "the only easy day was yesterday",
  "if you ain’t shaking, you ain’t making",
  "don’t just lift—bully the iron",
  "you’re either training or decaying",
  "every drop of sweat is rent paid in full",
  "don’t train like you’ll quit, train like you’ll conquer",
  "oh look, another almost-rep, congrats",
  "are you lifting or just waving at ghosts?",
  "your water bottle’s working harder than you",
  "you call that squat depth? adorable",
  "don’t worry, no one noticed your half push-up",
  "mirrors aren’t for selfies today, champ",
  "your playlist is stronger than your set",
  "benching air? bold choice",
  "didn’t know invisible pull-ups were a thing",
  "that rep was brought to you by disappointment",
  "keep moving, the gym floor isn’t lava",
  "nearly counts in horseshoes, not deadlifts",
  "lift like your ex is watching",
  "plank until the earth rotates away",
  "rep it out like rent’s due",
  "imagine every squat is a toilet emergency",
  "lift like the WiFi’s on the top shelf",
  "push until you can taste colours",
  "pretend the weights insulted your mum",
  "deadlift like zombies are chasing",
  "squat like you dropped your keys in hell",
  "run like free tacos are at the finish",
  "curl until your arms file for divorce",
  "plank like you’re dodging Lego on the floor",
  "add one more rep than you want to",
  "train like the camera’s always on",
  "your sweat owes you interest",
  "strong mind, stubborn muscles",
  "finish the set before the set finishes you",
  "be the reason the bar shakes",
  "set the pace, break the plateaus",
  "tired is a feeling, finished is a fact",
  "your warm-up is someone else’s workout",
  "turn doubts into deadlifts",
  "stop negotiating with your limits",
  "rep till your excuses get quiet",
  "show up messy, leave mighty",
  "build the habit, the habit builds you",
  "stack work, not wishes",
  "the only bad set is the skipped one",
  "pressure makes diamonds and delts",
  "you don’t need perfect—just present",
  "outlift your last excuse",
  "chase form, strength follows",
  "do the work you avoid",
  "make it heavy, make it happen",
  "check ego, cash effort",
  "today’s 1% beats tomorrow’s promise",
  "motion before emotion",
  "turn the music up and the doubt down",
  "your grind should make noise",
  "proof > promise",
  "sweat now, brag later",
  "earn the soreness",
  "discipline clocks in, motivation calls in sick",
  "be the engine, not the passenger",
  "training wheels off, plates on",
  "volume builds virtue",
  "fail forward, re-rack, repeat",
  "goal weight > body weight (on the bar)",
  "you don’t rise to the occasion—you fall to your training",
  "quit the quit",
  "if it’s easy, you’re early",
  "turn reps into routine",
  "move clean, move mean",
  "your future strength is watching today",
  "beat the buzzer, beat the doubt",
  "your pace, your race, your PB",
  "leave comfort at the door",
  "no coasting on leg day",
  "bite down, push up",
  "build consistency you can’t talk your way out of",
  "when it burns, you’re earning",
  "make fatigue your intern",
  "one strong decision, repeated",
  "make gravity your rival",
  "bank effort like savings",
  "proof of work due today",
  "loud lungs, quiet excuses",
  "no shortcuts, just reps",
  "heavy today, humble forever",
  "stack plates, stack character",
  "count reps, not reasons",
  "effort looks good on you",
  "breathe, brace, believe",
  "earn your endorphins",
  "make the last rep the best rep",
  "comfort is cancelled",
  "pace yourself, then race yourself",
  "upgrade your standard, not just your stats",
  "consistency turns minutes into muscle",
  "be allergic to almost",
  "leave one in the tank, then steal it back",
  "don’t skip the sticky reps",
  "learn the lift, respect the load",
  "make sweat a signature",
  "train today, thank yourself tomorrow",
  "courage for sixty seconds—go",
  "progress has a noise: your breath",
  "build the base before the flex",
  "set the tone with set one",
  "patience lifts heavier than pride",
  "no fast-forward on strength",
  "be coachable, even to yourself",
  "legs feed the wolf—squat",
  "own the tempo, own the set",
  "discipline tastes like water—drink it",
  "stack the wins you can control",
  "start where you stand",
  "don’t decorate the gym, dominate it",
  "your standard starts at rep one",
  "aim steady, add weight",
  "small hinges swing heavy doors",
  "be on time for your goals",
  "don’t waste the warm-up",
  "normalize hard things",
  "leave doubt on read",
  "respect the rest, then get back to work",
  "beat yesterday by one inch",
  "make failure part of the plan",
  "chase clean reps, not clout",
  "clock in, lock in, rock in",
  "stop scrolling, start squatting",
  "your pace is sacred—protect it",
  "sweat equity compounds",
  "own the last 10%",
  "write your program in effort",
  "grind today, flex tomorrow",
  "every rep is rent for your goals",
  "rest is fuel, not a lifestyle",
  "quit doubt before you quit reps",
  "push until silence feels loud",
  "your playlist can’t lift for you",
  "strong is a daily decision",
  "discipline tastes bitter but builds sweet",
  "don’t pause the set, pause the excuses",
  "energy spent beats energy wasted",
  "you’re not sore, you’re charging",
  "lift like it’s the last bar on earth",
  "every bead of sweat is a receipt",
  "future strength invoices today",
  "the floor isn’t hungry, why are you lying on it?",
  "train till mirrors say thank you",
  "no trophies for half-reps",
  "don’t ghost your gains",
  "gravity owes you nothing—earn it",
  "prove tired wrong",
  "every plank is a promise kept",
  "shortcuts rob strength",
  "stop planning, start lifting",
  "weights don’t care who you are",
  "proof is pain plus progress",
  "lift until doubt breaks",
  "skip excuses, not reps",
  "strength doesn’t DM you back, you gotta chase",
  "fail, reset, repeat stronger",
  "make work ethic your warm-up",
  "every pull is progress",
  "comfort ends where muscle begins",
  "your sweat is your signature",
  "today’s sets, tomorrow’s stories",
  "the mirror only reflects effort",
  "push like pride is watching",
  "pain is passing, pride is permanent",
  "the grind is honest currency",
  "earn your rest with your reps",
  "discipline never ghosts you",
  "lift heavy, live light",
  "prove weakness wrong daily",
  "your limits lied to you",
  "work until whispers become roars",
  "muscle is made from minutes",
  "reps are bricks, build your fortress",
  "the barbell is truth serum",
  "consistency cashes cheques motivation can’t",
  "don’t daydream under the dumbbell",
  "one rep braver than yesterday",
  "progress is louder than promises",
  "lift like your goals depend on it",
  "excuses weigh more than plates",
  "this set is your statement",
  "no finish line, only checkpoints",
  "prove your sweat is worth it",
  "don’t decorate the gym, dominate it",
  "the set starts when it hurts",
  "your pace is personal, but effort is universal",
  "get greedy for progress",
  "don’t give gravity free wins",
  "pain today, power unlocked",
  "work ethic > wifi signal",
  "show your goals who’s boss",
  "if it’s light, you’re lying",
  "consistency is the best coach",
  "every set writes your story",
  "patience is the heaviest plate",
  "fight fatigue with form",
  "don’t hope—rep",
  "train until sore feels normal",
  "earn your calories",
  "don’t text during sets, text after gains",
  "make the barbell your business partner",
  "you vs. iron: no ties",
  "respect the rep, respect yourself",
  "comfort is cancelled, check the schedule",
  "workouts don’t ghost you, you ghost them",
  "grind louder than excuses",
  "one small win ruins doubt",
  "never soft, always steady",
  "power hides in persistence",
  "the dumbbell doesn’t care about drama",
  "you’re not lifting, you’re building proof",
  "discipline outlasts hype",
  "tired is temporary, tough is timeless",
  "don’t scroll, squat",
  "your training speaks louder than talk",
  "push effort until it pushes back",
  "strength respects no shortcuts",
  "your mindset is the heaviest weight",
  "chase work, not wishes",
  "set goals, set PRs",
  "the gym pays in progress",
  "comfort zones pay minimum wage",
  "your discipline is your spotter",
  "the grind rewards silence",
  "train savage, stay humble",
  "pain teaches, pride celebrates",
  "weights bend for no one",
  "no one regrets discipline",
  "rep till doubt disappears",
  "work beats wishing, always",
  "effort today is flex tomorrow",
  "your muscles don’t speak excuses",
  "build effort equity",
  "heavy today, heroic tomorrow",
  "the set doesn’t care about your mood",
  "push plates, push limits",
  "your goals won’t chase you",
  "discipline pays compound interest",
  "rest is earned, not assumed",
  "make gravity beg for mercy",
  "every workout is proof of loyalty",
  "courage lasts one rep longer",
  "progress hides behind hard",
  "the grind accepts no bribes",
  "your sweat writes the receipts",
  "discipline builds destiny",
  "skip doubt, stack plates",
  "your comfort zone is broke",
  "show excuses the exit door",
  "make strength a daily deposit",
  "you’re stronger than lazy thoughts",
  "consistency is king, crown yourself",
  "don’t cheat the set, cheat excuses",
  "build respect under the bar",
  "rep until results argue back",
  "the clock doesn’t care, keep moving",
  "your strength owes rent—pay up",
  "form first, pride later",
  "effort is non-negotiable",
  "gravity wants you weak—fight it",
  "comfort whispers, discipline roars",
  "today is proof, not promise",
  "discipline is the currency of strength",
  "show fatigue who’s boss",
  "train for progress, not pity",
  "every sweat drop funds tomorrow",
  "don’t admire effort—do it",
  "pain is progress in disguise",
  "no breaks for excuses",
  "be addicted to small wins",
  "rep until your thoughts shut up",
  "consistency stacks louder than words",
  "don’t rent discipline, own it",
  "iron therapy > couch therapy",
  "earn respect from yourself",
  "the grind is your greatest ally",
  "comfort zones kill consistency",
  "lift until lazy leaves",
  "train harder than your excuses",
  "every rep is progress ink",
  "make failure part of your formula",
  "prove tired wrong with one more",
  "discipline builds armour",
  "the gym demands loyalty, not likes",
  "your body adapts to honesty",
  "progress doesn’t do discounts",
  "effort looks better than excuses",
  "chase sweat, not approval",
  "gravity is fair—fight back",
  "train till comfort fears you",
  "stop scrolling, start sweating",
  "don’t fake lifts, fake excuses",
  "patience plus plates equals progress",
  "consistency breaks ceilings",
  "your strength scares your past self",
  "discipline is louder than doubt",
  "push like tomorrow’s closed",
  "earn the soreness or stay the same",
  "don’t skip today’s bricks",
  "reps repay relentlessly",
  "prove fatigue fragile",
  "comfort zones breed weakness",
  "stack victories daily",
  "discipline is a habit, not a mood",
  "rep until your mindset shifts",
  "small wins swing big doors",
  "strength is stitched with sweat",
  "every workout builds character",
  "your excuses expire now",
  "gravity doesn’t forgive—fight harder",
  "work until progress owes you",
  "muscle is manufactured minutes",
  "discipline never discounts effort",
  "don’t pause for pity",
  "rep like your goals are watching",
  "train until your habits stick",
  "progress respects persistence",
  "your mood doesn’t set the weight",
  "earn progress pound by pound",
  "discipline dominates distraction",
  "show excuses the gym exit",
  "pain plus patience = progress",
  "the barbell asks for truth",
  "push plates, not problems",
  "don’t hide behind hope",
  "discipline multiplies results",
  "the gym isn’t therapy—it’s proof",
  "gravity is the only enemy worth fighting",
  "your PR is hiding in persistence",
  "comfort steals muscle",
  "the grind collects daily",
  "every rep = respect",
  "don’t waste discipline’s loyalty",
  "progress punishes hesitation",
  "effort beats ego",
  "show your past you who’s stronger",
  "be addicted to the hard parts",
  "the last rep is the real one",
  "train until excuses get sore",
  "discipline drinks sweat",
  "prove comfort zones wrong",
  "every bead of sweat is a step up",
  "don’t ghost the grind",
  "discipline > distraction, always",
  "progress is rented daily",
  "show up, shut up, lift up",
  "gravity doesn’t gossip—just grind",
  "iron judges fairly",
  "comfort zones bankrupt results",
  "discipline equals freedom under the bar",
  "skip the drama, stack the plates",
  "your set speaks louder than posts",
  "don’t cheat today’s contract",
  "discipline makes legends",
  "the grind remembers everything",
  "your sweat is your story",
  "excuses don’t pay muscle rent",
  "push until proud is the only option",
  "discipline > delay",
  "every rep proves potential",
  "make fatigue your forge",
  "comfort can’t coach you",
  "the bar never lies",
  "discipline writes destiny daily",
  "don’t argue with effort",
  "pain is proof of presence",
  "train until your future smiles",
  "discipline demands today",
  "comfort zones hire excuses",
  "progress > procrastination",
  "reps are receipts",
  "show yourself you’re serious",
  "the grind is your greatest gift",
  "train heavy, walk light",
  "discipline is self-respect",
  "don’t scroll while strength waits",
  "gravity is honest—meet it",
  "push until doubt is drowned",
  "discipline defines results",
  "work until excuses retire",
  "train till consistency is default",
  "comfort zones are closed",
  "earn progress in silence",
  "discipline pays in pride",
  "don’t stall, just lift",
  "the gym’s rent is effort",
  "progress shows no mercy",
  "discipline doesn’t do refunds",
];
/*
quick note:
generated with chatgpt
i am not writing nearly 500 original motivation one-liners
i wanna code and not write books haha
  */
